[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "build"
  exclude = [
    # By file Path
    './build/404.html',
    './build/success.html',
    './build/careers/junior-ux-designer.html',
    './build/careers/product-designer.html',
    './build/careers/ui-designer.html',
    './build/careers/ux-designer.html'
  ]